freeSeatsSearch:
  get:
    summary: "Получение списка свободных мест"
    parameters:
      - name: flightId
        in: query
        required: true
        schema:
          type: integer
    responses:
      200:
        description: "Список свободных мест был успешно получен"
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '../openapi.yaml#/components/schemas/Seat'
      400:
        description: "Полученные значения от клиента не прошли валидацию"
        content:
          application/json:
            schema:
              $ref: '../openapi.yaml#/components/schemas/ErrorResponse'
      404:
        description: "Список является пустым, мест не найдено"
        content:
          application/json:
            schema:
              $ref: '../openapi.yaml#/components/schemas/ErrorResponse'
      500:
        description: "Произошли ошибки на стороне сервера"
        content:
          application/json:
            schema:
              $ref: '../openapi.yaml#/components/schemas/ErrorResponse'